name = "showcase"
version = "0.1.0"
description = "A Gleam project"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.30"
lustre = "~> 3.0"
lustre_ui = { path = "../" }

[dev-dependencies]
gleeunit = "~> 0.10"
