name = "demo"
version = "0.1.0"
target = "javascript"
gleam = ">= 0.33.0"


[dependencies]
gleam_stdlib = "~> 0.34"
lustre = "~> 3.0"
lustre_ui = { path = "../" }

[dev-dependencies]
gleeunit = "~> 1.0"
